# -*- coding: utf-8 -*-
"""task3_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL7Amquid1nNS1FwR6Tk8akQX5lN00r8
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# 1. Load the dataset

file_path = "/content/drive/MyDrive/Mini Project 2/Data/churnguard_cleaned_data.csv"

cleaned_data = pd.read_csv(file_path)
data = cleaned_data

# 2. Encode the target column
data['Churn'] = data['Churn'].map({
    'Yes' : 1,
    'No' : 0
})

# 3. seperate x and y
y = data['Churn']
x = data.drop(columns = ['Churn'])

# 4. Encode categorical columns
categorical_columns = [
    "gender",
    "PhoneService",
    "InternetService",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

x = pd.get_dummies(
    x,
    columns=categorical_columns,
    drop_first=True
)

# 5. Split data into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2, random_state=42)

# 6. Train Logistic Regression model
model = LogisticRegression(max_iter = 1000)
model.fit(X_train, Y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

#Evaluate model
accuracy = accuracy_score(Y_test, y_pred)

print(f"Accuracy: {accuracy}")

# Print classification report
print("\nClassification Report:")

print(
    classification_report(
        Y_test,
        y_pred,
        target_names=["Stay", "Churn"]
    )
)

#Saving model to google drive
import joblib
from google.colab import drive
drive.mount('/content/drive')

# Now, save your model to a specific path in your Google Drive
# For example, in a 'models' folder in your Drive
model_drive_path = '/content/drive/MyDrive/Mini Project 2/Models/logistic_regression_model.joblib'

# Save the model to the specified path
joblib.dump(model, model_drive_path)

print(f"Model saved to Google Drive at: {model_drive_path}")