# -*- coding: utf-8 -*-
"""task2_clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRYIsaAiNyAXukobUZxiECX9_-iMyFXJ
"""

import pandas as pd

# Define the file path of the original dataset
file_path = "/content/drive/MyDrive/Mini Project 2/Data/churnguard_data.csv"

# Load the CSV file into a Pandas DataFrame
original_data = pd.read_csv(file_path)

# Create a reference to the original dataset
data = original_data

# Remove the customerID column as it is only an identifier
data = data.drop(columns=['customerID'])

# Display the first 5 rows of the dataset
data.head()

# Check the number of duplicate rows before removing them
print("Duplicate rows before removal:")
print(data.duplicated().sum())

# Remove duplicate rows
data = data.drop_duplicates()

# Check the number of duplicate rows after removing them
print("\nDuplicate rows after removal:")
print(data.duplicated().sum())

# Remove leading and trailing whitespace from the gender column
data['gender'] = data['gender'].str.strip()

# Remove leading and trailing whitespace from the PaymentMethod column
data['PaymentMethod'] = data['PaymentMethod'].str.strip()

# Remove whitespace and standardise Churn values to title case
data['Churn'] = data['Churn'].str.strip().str.title()

# Remove whitespace and standardise PhoneService values to title case
data['PhoneService'] = data['PhoneService'].str.strip().str.title()

# Remove whitespace and standardise PaperlessBilling values to title case
data['PaperlessBilling'] = data['PaperlessBilling'].str.strip().str.title()

# Define a mapping to standardise all variations of Contract values
contract_mapping = {
    "Month-to-month": "Month-to-month",
    "month-to-month": "Month-to-month",
    "Month to month": "Month-to-month",
    "One year": "One year",
    "one year": "One year",
    "1 year": "One year",
    "Two year": "Two year",
    "two year": "Two year",
    "2 year": "Two year"
}

# Standardise the Contract column using the mapping
data['Contract'] = data['Contract'].str.strip().replace(contract_mapping)


# Display the current values in InternetService, including missing values
print("\nInternetService values before standardisation:")
print(data["InternetService"].value_counts(dropna=False))


# Define a mapping to standardise all variations of InternetService values
internetService_mapping = {
    "DSL": "DSL",
    "dsl": "DSL",
    "DSl": "DSL",
    "Dsl": "DSL",
    "Fiber optic": "Fiber optic",
    "fiber optic": "Fiber optic",
    "Fibre optic": "Fiber optic",
    "FiberOptic": "Fiber optic",
    "No": "No",
    "NO": "No",
    "no": "No"
}

# Standardise the InternetService column using the mapping
# Missing values remain unchanged because no rule was provided to fill them
data['InternetService'] = (
    data['InternetService']
    .str.strip()
    .replace(internetService_mapping)
)

# Display the InternetService values after standardisation
print("\nInternetService values after standardisation:")
print(data['InternetService'].value_counts(dropna=False))

# Convert TotalCharges to numeric values
# Invalid or non-numeric values are converted to NaN
data['TotalCharges'] = pd.to_numeric(
    data['TotalCharges'],
    errors="coerce"
)

# Remove rows where tenure is zero or negative
data = data[data['tenure'] > 0]


# Remove rows where MonthlyCharges is less than 10
# or greater than 200
data = data[
    (data["MonthlyCharges"] >= 10) &
    (data["MonthlyCharges"] <= 200)
]

# Fill missing MonthlyCharges values with the column mean
data['MonthlyCharges'] = data['MonthlyCharges'].fillna(
    data['MonthlyCharges'].mean()
)

# Fill missing TotalCharges values with the column mean
data['TotalCharges'] = data['TotalCharges'].fillna(
    data['TotalCharges'].mean()
)

# Calculate the median value of tenure
tenure_median = round(data['tenure'].median())

# Fill missing tenure values with the rounded median
data['tenure'] = data['tenure'].fillna(tenure_median)


# Display the shape of the cleaned dataset
print("\nShape of cleaned dataset:")
print(data.shape)


# Calculate the number of missing values in each column
missing_count = data.isnull().sum()

# Display the missing value count for each column
print("\nMissing values after cleaning:")
print(missing_count)

import os

# Define the output file path
output_file_path = os.path.join(os.path.dirname(file_path), "churnguard_cleaned_data.csv")

# Save the cleaned DataFrame to a new CSV file
data.to_csv(output_file_path, index=False)

print(f"Cleaned data saved to: {output_file_path}")

