# -*- coding: utf-8 -*-
"""task1_load_explore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-q6drRhWfkX5hzNtRA0FE7lqe4PYe98
"""

import pandas as pd

# Define the path to the churnguard dataset stored in Google Drive
file_path = "/content/drive/MyDrive/Mini Project 2/Data/churnguard_data.csv"

# Load the CSV file into a Pandas DataFrame
original_data = pd.read_csv(file_path)

# Create a reference to the original dataset
data = original_data

# Print the number of rows and columns in the dataset
print("Data shape: ", data.shape)

# Display the first 5 rows of the dataset
print("\nFirst 5 rows:")
print(data.head())

# Display column names, non-null counts, and data types
print("\nDataset information: ")
data.info()

# Count and display the missing values in each column
print("\nMissing column")
print(data.isnull().sum())

# Count and display the number of duplicate rows
print("Duplicate rows")
print(data.duplicated().sum())

# Display the frequency of each value in the Churn column
print("\nChurn value counts")
print(data['Churn'].value_counts())

# Display all unique values present in the Contract column
print("\nUnique values in Contract column")
print(data['Contract'].unique())